### ISSUE TITLE
send config in channel is not working ( I can't set channel_id )

### ISSUE THREAD

**Issue by GhostOfSarina** [hrostami/sb-server-configer#12]
Dear Developer,

As I send the request ```/set channel_id @my_channel```, Bot didn't send anything.

I find send a request in configer.py file
``` context.bot.send_message(chat_id=channel_id, text=encoded64)```

but I think it does not work properly, or I need more explanation about, how it works.

**Comment by GostOfSarina** [comment]
```/set channel_id @my_channel```


```

2023-05-24 07:45:10,188 ERROR An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/root/configer/configer.py", line 303, in user_data_handler
    value = int(input[2])
ValueError: invalid literal for int() with base 10: '@my_channel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 459, in process_update
    self.dispatch_error(update, exc)
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 679, in dispatch_error
    callback(update, context)
TypeError: 'MessageHandler' object is not callable
```

**Comment by GostOfSarina** [comment]
I found my channel_id , but still didn't work

```
https://gist.github.com/mraaroncruz/e76d19f7d61d59419002db54030ebe35
```

much easier way .. forward a message from that channel to this @JsonDumpBot bot
can voila there's your ID

**Comment by hrostami** [comment]
yes you should use the numeral id for your channel that you could get from myidbot in tg. Also it starts with -100.

**Comment by GhostOfSarina** [comment]
After a long time struggling with this system, I made another decision,
I added your project features to the [https://github.com/deathline94/sing-REALITY-Box](https://github.com/deathline94/sing-REALITY-Box) project.
And made another project [https://github.com/GostOfSarina/sing-box-daily-telegram](https://github.com/GostOfSarina/sing-box-daily-telegram)
